// This file was auto-generated by ML.NET Model Builder. 
using System.Linq;
using Microsoft.ML;

namespace ml_api.Models
{
  public partial class ReviewModel
  {
    public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
    {
      var pipeline = BuildPipeline(context);
      var model = pipeline.Fit(trainData);

      return model;
    }
    public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
    {
      // Data process configuration with pipeline data transformations
      var pipeline = mlContext.Transforms.Text.FeaturizeText(@"review", @"review")
                      .Append(mlContext.Transforms.Concatenate(@"Features", @"review"))
                      .Append(mlContext.Transforms.Conversion.MapValueToKey(@"sentiment", @"sentiment"))
                      .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))
                      .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(l1Regularization: 0.446059250239384F, l2Regularization: 0.0595710178571838F, labelColumnName: @"sentiment", featureColumnName: @"Features"))
                      .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

      return pipeline;
    }
  }
}
