FROM node:lts-alpine

RUN apk add --update --no-cache git && apk add --no-cache --virtual .gyp python make g++

WORKDIR /home/node/app

COPY package.json  /home/node/app/

RUN npm install

COPY . /home/node/app/

RUN node ace build --production

WORKDIR /home/node/app/build

RUN npm ci --production

EXPOSE 3333

CMD sh -c 'node server.js'