FROM node:lts-alpine

RUN apk add --update --no-cache git

WORKDIR /home/node/app

COPY package.json  /home/node/app/

RUN npm install

COPY . /home/node/app/

EXPOSE 3333

CMD sh -c 'node ace serve --watch'