name: Build
on:
  push:
    branches: [ dev, v2 ]
jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: cd client && docker build .
  build-ml-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: cd ml-api && docker build .